version: "3.9"
services:
  webserver:
    container_name: PHP-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./apache2.conf:/etc/apache2/apache2.conf
    ports:
      - 80:80